set nocompatible

noremap <left> <nop>
noremap <right> <nop>
noremap <up> <nop>
noremap <down> <nop>

set noswapfile

filetype plugin indent on

syntax on

set encoding=utf-8
set fileencoding=utf-8

set number
set ruler

set wildmenu

set list
set listchars=tab:▸\ ,eol:¬,nbsp:⋅,trail:•

set incsearch
set hlsearch
set smartcase

set expandtab
set shiftwidth=4
set softtabstop=4

set cursorline
set colorcolumn=80

map K r<Enter>

" Statusline {{{

hi User1 ctermbg=white    ctermfg=black   guibg=#89A1A1 guifg=#002B36
hi User2 ctermbg=red      ctermfg=white   guibg=#aa0000 guifg=#89a1a1

function! GetCWD()
    return expand(":pwd")
endfunction

function! IsHelp()
    return &buftype=='help'?' (help) ':''
endfunction

function! GetName()
    return expand("%:t")==''?'<none>':expand("%:t")
endfunction

set statusline=%1*[%{GetName()}]\
set statusline+=%<pwd:%{getcwd()}\
set statusline+=%2*%{&modified?'\[+]':''}%*
set statusline+=%{IsHelp()}
set statusline+=%{&readonly?'\ (ro)\ ':''}
set statusline+=[
set statusline+=%{strlen(&fenc)?&fenc:'none'}\|
set statusline+=%{&ff}\|
set statusline+=%{strlen(&ft)?&ft:'<none>'}
set statusline+=]\
set statusline+=%=
set statusline+=c%c
set statusline+=,l%l
set statusline+=/%L\

set laststatus=2

" }}}
