set nocompatible

set noswapfile

filetype plugin indent on

syntax on

set encoding=utf-8
set fileencoding=utf-8

set number
set ruler

set list
set listchars=tab:▸\ ,eol:¬,nbsp:⋅,trail:•

set incsearch
set hlsearch
set smartcase

set expandtab
set shiftwidth=4
set softtabstop=4

set cursorline
set colorcolumn=80

map K r<Enter>
