set nocompatible

noremap <left> <nop>
noremap <right> <nop>
noremap <up> <nop>
noremap <down> <nop>

set noswapfile

filetype plugin indent on

syntax on

set encoding=utf-8
set fileencoding=utf-8

set number
set ruler
set showcmd
set showmatch

set wildmenu
set wildignore=*.o,.deps,*.obj,*.bak,*.pyc

set list
set listchars=tab:▸\ ,eol:¬,nbsp:⋅,trail:•

set incsearch
set hlsearch
set smartcase

set smartindent
set autoindent

set expandtab
set shiftwidth=4
set softtabstop=4

set cursorline
set colorcolumn=80

set scrolloff=10

set history=500

set linebreak
set showbreak=>\ \ 

set foldmethod=marker
set foldmarker={{{,}}}

map K r<Enter>

let mapleader=','

nmap ; :

nmap <leader>s :source $MYVIMRC<cr>
nmap <leader>v :tabe $MYVIMRC<cr>

nmap <leader><space> :set hlsearch! hlsearch?<cr>

nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>

nmap j gj
nmap k gk
nmap 0 g0
nmap $ g$

nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-h> <C-W>h
nmap <C-l> <C-W>l

nmap <leader>tn :tabnew<cr>
nmap <leader>tc :tabclose<cr>
nmap <leader>to :tabonly<cr>

cnoreabbrev Wq wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q

cnoreabbrev wrap set wrap
cnoreabbrev nowrap set nowrap

" Statusline {{{
hi User1 ctermbg=white    ctermfg=black   guibg=#89A1A1 guifg=#002B36
hi User2 ctermbg=red      ctermfg=white   guibg=#aa0000 guifg=#89a1a1

function! GetCWD()
    return expand(":pwd")
endfunction

function! IsHelp()
    return &buftype=='help'?' (help) ':''
endfunction

function! GetName()
    return expand("%:t")==''?'<none>':expand("%:t")
endfunction

set statusline=%1*[%{GetName()}]\
set statusline+=%<pwd:%{getcwd()}\
set statusline+=%2*%{&modified?'\[+]':''}%*
set statusline+=%{IsHelp()}
set statusline+=%{&readonly?'\ (ro)\ ':''}
set statusline+=[
set statusline+=%{strlen(&fenc)?&fenc:'none'}\|
set statusline+=%{&ff}\|
set statusline+=%{strlen(&ft)?&ft:'<none>'}
set statusline+=]\
set statusline+=%=
set statusline+=c%c
set statusline+=,l%l
set statusline+=/%L\

set laststatus=2
" }}}

" Tab completion {{{
function! InsertTabWrapper()
    let col = col(".") - 1
    if !col ||getline(".")[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-n>"
endfunction

inoremap <tab> <c-r>=InsertTabWrapper()<cr>
inoremap <s-tab> <c-p>
" }}}
